## libraries
```{r}
#| echo: true
#| message: false
library(BiocParallel)
library(colorRamps)
library(RColorBrewer)
library(biomaRt)
```

## variables
```{r}
# deseq2 parameters
pval <- 0.05
qval <- 0.05
lfc <- 1

# low read counts filter cutoff
filt <- 20

# date and cores
date <- format(Sys.Date(), format = "%Y%m%d")
nc <- BiocParallel::multicoreWorkers()

# colors
blp <- colorRampPalette(rev(brewer.pal(9, "Blues")))(255)
ryb <- colorRampPalette(rev(brewer.pal(n = 7, name = "RdYlBu")))(100)

# seed
set.seed(888)
```

## genome
```{r}
# /data/project/MillerLab/genomes/GRCm39_vM37

# import tx2gene (contains 3 columns)
# Col 1 - Ensembl txID [transcript_id]
# Col 2 - Ensembl geneID [gene_id]
# Col 3 - gene_name

tx_geneID_genename <- read.delim2(
    file = "/data/input/tx2gene.tsv",
    header = TRUE, sep = "\t")
colnames(tx_geneID_genename)

tx_gene_symbol <- tx_geneID_genename[-2] # remove gene_id column
head(tx2gene_symbol)

tx_gene <- tx_geneID_genename[-3] # remove gene_name column
head(tx_gene)

## ID2Symbols
genes <- tx_gene_symbol$gene_name
length(genes)
mart <-
  useEnsembl(biomart = "ensembl",
             dataset = "mmusculus_gene_ensembl",
             mirror = "useast")
genes_mouse <-
  biomaRt::getBM(
    attributes = c(
      "ensembl_gene_id_version",
      "mgi_id",
      "mgi_symbol",
      "chromosome_name",
      "strand",
      "start_position",
      "end_position",
      "description",
      "gene_biotype"
    ),
    filters = "external_gene_name",
    values = genes,
    mart = mart
  )
write.csv(genes_mouse, file = paste0(dir_output, "genes_mouse_vM37.csv"))
genes_mouse %>%
  group_by(gene_biotype) %>%
  summarize(n = n())
```

## pcg
```{r}
pcg <-
  subset(genes_mouse, genes_mouse$gene_biotype == "protein_coding")
dim(pcg)
pcg_df <- pcg

## Remove "RIKEN" genes
pcg_df <- pcg_df[!grepl("RIKEN", pcg_df$description), ]
dim(pcg_df)
## Remove "cDNA sequence" genes
pcg_df <- pcg_df[!grepl("cDNA sequence", pcg_df$description), ]
dim(pcg_df)
## Remove "DNA segment" genes
pcg_df <- pcg_df[!grepl("DNA segment", pcg_df$description), ]
dim(pcg_df)
## Remove "predicted gene" genes
pcg_df <- pcg_df[!grepl("predicted gene", pcg_df$description), ]
dim(pcg_df)
## Remove "MT" chromosomes
pcg_df <- subset(pcg_df, pcg_df$chromosome_name != "MT")
dim(pcg_df)
## Include only somatic chromosomes
pcg_df <- subset(pcg_df, pcg_df$chromosome_name %in% c(1:19, "X", "Y"))
dim(pcg_df)
write.csv(pcg_df, file = paste0(dir_output, "genes_mouse_vM37_pcg.csv"))

pcg <- as.vector(pcg_df$mgi_symbol)
```

## genesets
```{r}
# kinases
file_kinases <- "./genesets/201006_composite_kinases.csv"
if (file.exists(file_kinases)) {
  kinases <- read.csv(file_kinases, header = TRUE, fileEncoding = "UTF-8-BOM")
} else {
  stop(paste("File not found:", file_kinases))
}
str(kinases)
head(kinases)
kinase_genes <- kinases$Mouse_symbol
```